### ISSUE TITLE
parse failed: template: posts/single.html:142: unexpected EOF

### ISSUE THREAD

**Issue by sshawarma** [rhazdon/hugo-theme-hello-friend-ng#207] opened 2020-09-06 00:00 UTC
I'm very new to Hugo and its templating language, so bear with me. I ran `hugo server -D` after adding the theme to my `themes/` folder using `git submodule add https://github.com/rhazdon/hugo-theme-hello-friend-ng.git themes/hello-friend-ng`. I got the following output:

```
Built in 78 ms
Error: Error building site: "/Users/ssharma/code/sshawarma.github.io/themes/hello-friend-ng/layouts/posts/single.html:142:1": parse failed: template: posts/single.html:142: unexpected EOF
```

I figured out that the error was on line 78 of in `/layouts/posts/single.html`, which is:

```
{{ if .LastMod }} ({{ i18n "lastModified" }}: {{ if .Site.Params.dateformNumTime }}{{ dateFormat .Site.Params.dateformNumTime .LastMod.Local }}{{ else }}{{ dateFormat "2006-01-02 15:04 -0700" .LastMod.Local }}){{ end }}
```
I sort of fixed the "unexpected EOF" error by adding an `{{ end }}` before the final `)`:

```
{{ if .LastMod }} ({{ i18n "lastModified" }}: {{ if .Site.Params.dateformNumTime }}{{ dateFormat .Site.Params.dateformNumTime .LastMod.Local }}{{ else }}{{ dateFormat "2006-01-02 15:04 -0700" .LastMod.Local }}{{ end }}){{ end }}
```
After I did this, Hugo gave me another error:

```
Built in 56 ms
Error: Error building site: failed to render pages: render of "page" failed: "/Users/ssharma/code/sshawarma.github.io/themes/hello-friend-ng/layouts/posts/single.html:78:14": execute of template failed: template: posts/single.html:78:14: executing "main" at <.LastMod>: can't evaluate field LastMod in type *hugolib.pageState
```

I don't know enough about Hugo to solve this problem, so I just removed this line of code. I ran `hugo server -D` again and Hugo ran without errors.

I didn't find anyone else with this problem, so I'm hoping that the mistake was just on my end.

**Comment by rosalogia** [comment] 2020-09-06 02:41
I'm also experiencing this problem

**Comment by rhazdon** [comment] 2020-09-06 07:19
Hi @sshawarma, thanks for the report. It seems there is an relation to the last added feature (last mod date). I am currently working on a solution.

**Comment by rhazdon** [comment] 2020-09-06 07:58
Hi @sshawarma and @rosalogia,

the issue is fixed now. I apologize for the inconvenience. I should have checked the merge request better.

**Closed** 2020-09-11 11:10 UTC
